# 两因素实验设计 {#towfactors}

多因素实验设计不仅可以探讨各个自变量的作用，还可以探讨多个因素之间的交互作用，故而获得更多的信息，实验效率也更高。

## 两因素完全随机实验设计

> 文章类型与句子长度对学生阅读理解能力有影响

### 前提条件

1. 因变量在每个实验单元内部都为正态分布，否则要求每个单元格15人以上才可以提高方差分析结果的可信度。
1. 因变量在所有实验单元内方差齐性，否则分析结果不可信。
1. 因变量在各个实验单元内相互独立，否则分析结果不可信。
1. 因变量应该为连续性变量。

### 统计分析思路

1. 检验A因素的主效应。
1. 检验B因素的主效应。
1. 检验A*B的交互效应。
1. 当交互效应显著时，需要进一步做简单效应的检验。

### SPSS中的实现

[练习数据](data/2factors-random.sav)

1. 定义A、B以及因变量，输入数据。
1. 选择分析下的一般线性模型，再选单因变量方差分析。
1. 根据研究假设，分别确定因变量和固定变量。
1. 点击图，选定A为横坐标，B为独立拆线，或者相反，或者两者组合。
1. 选择事后比较，对B的三个水平进行多重比较，在假设方差齐性的方法中，勾选tukey法，在不齐性的方法中任选一个。在多因素方差分析中，如果某因素主效应显著，而其他交互效应不显著时，应该进行各因素水平之间均数的多重比较。而当交互效应显著时，则进行简单效应检验，而无需进行多重比较。
1. 在选项对话框中，选择描述性统计、效应度检验、统计检验力检验、方差齐性检验。
1. 执行分析程序。

如果a*b存在交互效应，还需要进行简单效应检验。由于spss没有提供进行简单效应检验的菜单，需要运行程序语句实现。

在原来语句的基础上：

```
UNIANOVA 成绩 BY 文章类型 句子长度 
  /METHOD=SSTYPE(3) 
  /INTERCEPT=INCLUDE 
  /POSTHOC=句子长度(TUKEY) 
  /PLOT=PROFILE(文章类型*句子长度) TYPE=LINE ERRORBAR=NO MEANREFERENCE=NO YAXIS=AUTO 
  /PRINT ETASQ DESCRIPTIVE HOMOGENEITY OPOWER 
  /CRITERIA=ALPHA(.05) 
  /DESIGN=文章类型 句子长度 文章类型*句子长度.
```

修改为：

```
UNIANOVA 成绩 BY 文章类型 句子长度 
  /METHOD=SSTYPE(3) 
  /INTERCEPT=INCLUDE 
  /EMMEANS = TABLES(文章类型*句子长度) COMPARE(句子长度) ADJ(SIDAK) 
  /EMMEANS = TABLES(句子长度*文章类型) COMPARE(文章类型) ADJ(SIDAK) 
  /CRITERIA=ALPHA(.05) 
  /DESIGN=文章类型 句子长度 文章类型*句子长度.
```

其中，`/EMMEANS = TABLES(a*b) COMPARE(b) ADJ(SIDAK)`的功能为，在a的各水平上，检验b变量不同水平差异的显著性。

### SPSS 分析结果的解读

1. 描述统计结果，计算出了因变量在各实验单元中的均值、标准差以及被试数。
1. 方差齐性检验结果，看p值。
1. 被试间效应检验结果中：
   1. 修正模型，其平方和为a因素平方和、b因素平方和、a*b交互效应平方和之总和。
   1. 截距，检验因变量的总均值是否为零。
   1. a因素主效应看p值。如果显著，说明a因素对因变量有显著影响，效应度为xxx，统计检验力为xxx。效应度=因素平方和/(因素平方和+误差平方和)。统计检验力为正确拒绝零假设的概率。
   1. b因素主效应的解读同a。
   1. a*b交互效应的显著性看p值，若显著，说明a与b对因变量有显著的交互影响，其效应度为xxx，统计检验力为xxx。
   1. 总平方和为截距和校正模型之和。
   1. 校正总和，代表模型所解释的变异与误差变异的总和。
1. 多重比较能够发现哪些具体的组合差异存在显著性。
1. 均值显示图，可以大致判断因素之间是否存在交互效应。
1. 简单效应，看a*b（成对比较）检验结果，根据p值，对具体存在的简单效应进行判断。

## 两因素混合实验设计

混合实验是最常用的多因素实验设计类型，它既不像完全随机实验设计需要较多的被试，也不像重复测量实验设计那样因为重复测量而存在累积效应。当有些变量适合被试内、有些变量适合被试间时，使用混合实验设计。

### 两因素混合实验设计的前提条件

1. 因变量在每个实验单元内部都为正态分布，否则要求每个单元格15人以上才可以提高方差分析结果的可信度。
1. 因变量在因素任意两个水平间的方差相等。备选方差分析和多元方差分析不受方差齐性的限制。
1. 样本必须从总体中随机抽取获得，被试间相互独立。
1. 多元方差分析还需要多元正态性，即每个差值变量都呈正态分布，但大样本不受限制。
1. 多元方差分析也需要样本从总体中随机抽取，且各差值之间相互独立。

### 两因素混合实验的基本特点

1. 在两个自变量中，一个是被试内变量，另一个是被试间变量。
1. 相对于被试间因素的处理效应，实验者更关注被试内因素的处理效应，以及其与被试间因素之间的交互效应。
1. 被试间变量有几个水平就有几个实验组，随机选取被试，随机分配到各实验组。

### 分析思路

1. 如果被试内变量b主效应显著，而a*b交互效应不显著，则应进行多重比较。（变量的水平超过2个就需要进行）
1. 如果交互效应显著，还需进行简单效应检验。

### 两因素混合实验的SPSS实现

1. 定义变量及输入数据。将被试间变量定义为1个变量，被试内变量按照水平分别进行定义。
1. 选择分析菜单中的一般线性模型，选择重复测量。
1. 在被试内变量名，设置被试内变量b，在定义变量水平数的方框中，输入b的水平数，点击添加。
1. 点击定义对话按钮，在对话框中，将a选入被试间因素中，将b的不同水平选入被试内变量中。
1. 在绘图对话框中，分别将a、b作为横坐标和独立线，添加绘图中。
1. 在选项对话框中，选择描述性统计、效应度检验、统计检验力检验、方差齐性检验。
1. 在EM对话框中，将被试内变量b选入右侧的显示均值中，选择LSD进行多重比较。
1. 点击确定，运行分析。

如果a*b交互作用显著，还需要进行简单效应检验。分析方式同两因素完全随机。例如：

```
GLM b1 b2 b3 BY a 
  /WSFACTOR=b 3 Polynomial 
  /METHOD=SSTYPE(3) 
  /EMMEANS = TABLES(a*b) COMPARE(b) ADJ(SIDAK)
  /EMMEANS = TABLES(b*a) COMPARE(a) ADJ(SIDAK)
  /CRITERIA=ALPHA(.05) 
  /WSDESIGN=b 
  /DESIGN=a.
```


### 两因素混合实验分析结果的解读

1. 描述统计结果中，可以看出处理单元内的均值、标准差及被试数量。
1. 方差齐性检验，看p值进行决策（各组因变量协方差矩阵是否相等），如各实验党员内的数据大于15，则不需要考虑方差是否齐性。
1. 多元方差分析结果表，看被试内变量b的主效应是否显著，b*a的交互效应是否显著。
1. 球形检验结果如果不满足（p值小于0.05），用备选一元方差分析（Greenhouse-Geisser）与多元方差分析的结果，如果满足（p值大于0.05），可用标准一元方差分析结果。得出被试内变量b的主效应显著度、效应度和统计检验力以及b*a的显著度、效应度和统计检验力。
1. 方差齐性看p值进行决策（选择何种事后检验方法）。
1. 被试间变量主效应检验结果，根据p值，进行决策，如果显著，还需明确说明在什么水平上高。
1. 描述性统计结果和多重比较结果结合，可以看出被试内的差异，在什么组合条件下存在统计显著性。
1. 均值图，折线如果不平行，则可大致判断出两个因素之间存在交互效应
1. a*b 简单效应检化验结果中，可以看出具体的简单效应在什么情况下存在，结合描述性统计表，进行汇报。例如：`在xx条件下，被试在xxx时的xxx显著高于xxx时的xxx（p=xxx）`。

## 两因素重复测量实验设计

两因素重复测量实验设计也是常用的实验设计。两因素重复测量的方差分析，能将被试间变异（个体差异引起的变异）从总变异中分离出来。由于被试需要接受多次测试，因此容易产生练习效应和疲劳效应，可通过随机材料和分阶段完成实验的方式加以改进。

### 两因素重复测量实验设计的前提条件

1. 因变量在每个实验单元内部都为正态分布，否则要求每个单元格15人以上才可以提高方差分析结果的可信度。
1. 因变量在因素任意两个水平间的方差相等。备选方差分析和多元方差分析不受方差齐性的限制。
1. 样本必须从总体中随机抽取获得，被试间相互独立。
1. 多元方差分析还需要多元正态性，即每个差值变量都呈正态分布，但大样本不受限制。
1. 多元方差分析也需要样本从总体中随机抽取，且各差值之间相互独立。

### 两因素重复测量实验的基本特点

1. 在两个自变量中，均为被试内变量。
1. 如果一个自变量有p个水平，另一有q个水平，该实验就有p*q个实验处理水平的结合。
1. 只有一个实验组，随机选组N个被试，每个被试都要接受p*q次实验处理。

### 两因素重复测量实验的SPSS数据分析

[练习数据](data/2factors-repeat.sav)

1. 定义变量及输入数据。按照实验处理水平的结合，分别定义变量名。
1. 选择分析菜单中的一般线性模型，选择重复测量。
1. 按照变量特征，定义好被试内变量a、b，点击添加。
1. 在重复测量对话框中，将结合变量名分别按顺序键入到被试内变量中。
1. 在绘图对话框中，分别将a、b作为横坐标和独立线，添加绘图中。
1. 在选项对话框中，选择描述性统计、效应度检验、统计检验力检验、方差齐性检验。
1. 在EM对话框中，将被试内变量b（水平数大于2）选入右侧的显示均值中，选择LSD进行多重比较。
1. 点击确定，运行分析。

如果a*b交互作用显著，还需要进行简单效应检验。分析方式同两因素完全随机。例如：

```
GLM a1b1 a1b2 a1b3 a2b1 a2b2 a2b3 
  /WSFACTOR=a 2 Polynomial b 3 Polynomial 
  /METHOD=SSTYPE(3) 
  /EMMEANS = TABLES(a*b) COMPARE(b) ADJ(SIDAK)
  /EMMEANS = TABLES(b*a) COMPARE(a) ADJ(SIDAK)
  /PRINT=DESCRIPTIVE ETASQ OPOWER HOMOGENEITY 
  /CRITERIA=ALPHA(.05) 
  /WSDESIGN=a b a*b.
```

### 两因素重复测量实验分析结果的解读

1. 描述统计结果，计算除了各个实验处理水平结合条件下的平均值、标准差及被试数。
1. 多元方差分析结果，看a、b、a*b的效应是否显著，其效应度和统计检验力分别为多少。
1. 球形检验结果如果不满足（p值小于0.05），用备选一元方差分析（Greenhouse-Geisser）与多元方差分析的结果，如果满足（p值大于0.05），可用标准一元方差分析结果。
1. 一元方差分析结果得出被试内变量的主效应显著度、效应度和统计检验力以及b*a的显著度、效应度和统计检验力。
1. 因素b各水平间的多重比较结果，需要结合描述性统计结果表，对不同水平间是否存在统计显著性差异决出决策。
1. 均值图如果有交叉趋势，可以大致判断两个因素之间存在交互效应。
1. a*b 简单效应检验结果中，可以看出具体的简单效应在什么情况下存在，结合描述性统计表，进行汇报。例如：`在xx条件下，被试在xxx时的xxx显著高于xxx时的xxx（p=xxx）`。

## 小结

在方差分析中，误差项越多，其数值相对越小，与其相对应的F检验就越敏感，亦即F检验的精度也就越高。据此，相对而言，两因素完全随机实验设计的精度最低，两因素混合实验设计的精度次之，两因素重复测量实验设计的精度最高。
